### ISSUE TITLE
 Mnemonic & Private keys are different - Please update readme

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/ocean-cli#22]
### Problem
The readme communicates 2 different concepts as if they're the same.

```
Set a private key and export it
export MNEMONIC="XXXX"
```

Mnemonics are the 12-word random keys required to generate private keys. In barge this is preconfigured so you always get the same private keys.
```
export GANACHE_MNEMONIC=${GANACHE_MNEMONIC:-"taxi music thumb unique chat sand crew more leg another off lamp"}
```

private-key is the 0x hash associated with a specific EOA
```
0xfd5c1ccea015b6d663618850824154a3b3fb2882c46cefb05b9a93fea8c3d215
```

### DoD:
- [ ] Clean up mnemonic/private key in README so it's obvious to the user
- [ ] Perhaps provide an example of what you're looking for
```
export MNEMONIC="taxi music thumb..."
```
or 
```
export PRIVATE_KEY="0xfd5c1ccea015b6d66...."
```

**Comment by mihaisc** [comment]
Thanks for noticing. Change the var to PRIVATE_KEY since we are actually using only the private key. For mnemonic we should use fromMnemonic but doesn't make sense to implement it right now
