### ISSUE TITLE
The aquarius-url doesn't have a default value

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean-cli#26]
The CLI should use by default the https://v4.aquarius.oceanprotocol.com/ aqua. 
Currently, if the user doesn't do export AQUARIUS_URL='XXXX', the aquarius_url is null and the operations fail.

![Screenshot 2023-10-05 at 18 38 42](https://github.com/oceanprotocol/ocean-cli/assets/84312885/d7f91974-10ef-40ed-80e7-cb0fa579a623)

**Comment by AnaLoznianu** [comment]
@mihaisc I suggest we include this in Q4 as well

**Comment by alexcos20** [comment]
See #23
