### ISSUE TITLE
Create interactive publish function

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-cli#70]
Create a function with multiple steps that helps you publish an asset

ex:
1. what themplate do you want to use 1,2,4?
2. What is the name of the asset
3.  ...

We can get inspired from the current publish screen in the market https://market.oceanprotocol.com/publish/1

**Comment by jamiehewitt15** [comment]
I suggest that we start with the easy questions (e.g. title and description) and then move onto the more technical questions e.g. which network? And then lastly, we can have a question "Would you like to see advanced options?" which could include things like user-defined parameters.  

It needs a bit more refining but the order could potentially be something like this: 

1. What is the title of your asset? 
2. Please provide a description of your asset? 
3. Who is the Author of this asset?
4. Please provide tags to make this asset more easily discoverable: 
5. After purchasing your asset, how long should the consumer be allowed to access it for? 
6. How is your asset stored? IPFS / Arweave / URL
7. Please provide the {url / hash / txID } for your asset?
9. Will you charge for this asset? 
10. [optional] What token will you accept payments in? 
11. [optional] What is the price to access your asset?
12. What network will your asset be available for purchase though? {default: Oasis Saphire}
13. [Optional if they don't pick oasis] Which template would you like to use + explanation on the options. 
14. Would you like to consider all of the advanced options for your asset? {default: no}
